### PR TITLE
Swift Package Manager Support

### PR DESCRIPTION
**Pull request by verticon**
I’ve made changes that allow RNCryptor to be used with the SwiftPM.

In order to see it in action, do the following

1. Open a terminal
2. Execute => mkdir name; cd name
3. Execute => swift package init —type executable
4. Edit Package.swift so that the contents are as follows:

import PackageDescription

let package = Package(
    name: "Main",
    dependencies: [
        .Package(url: "https://github.com/verticon/RNCryptor.git", majorVersion: 5)
    ]
)

5. Edit Sources/main.swift so that the contents are as follows:

import Foundation
import RNCryptor

let password = "password"

func measure(block: () -> Void) {
    let start = Date()
    block()
    print("Execution time = \(Date().timeIntervalSince(start))")
}

let size = 100_000_000
let data = RNCryptor.randomData(ofLength: size)
measure {
    print("Encrypting \(size) bytes")
    _ = RNCryptor.encrypt(data: data, withPassword: password)
}

6. Execute => swift build

7. Execute =>  ./.build/debug/Main. You should see output similar to:

Encrypting 100000000 bytes
Execution time = 0.576680958271027

You can find the cloned repo in the Packages folder. Besides reorganizing the files to conform to the SwiftPM’s conventions, the primary “challenge” was expressing the dependency of RNCryptor.swift upon RNCryptor.h. This was accomplished by putting RNCryptor.h in a separate module.

I have not yet accomplished the above steps on Ubuntu: the C compiler cannot yet locate all the required header files.

Finally, I had to add the tag ‘5.0.2’ to the repo. The SwiftPM will not match against tags such as RNCryptor-5.0.1

### CODE REVIEW

**Comment by rnapier** [comment]
Does it make more sense for "Cryptor" to be called "CommonCrypto" since that's what it's trying to be?

**Comment by rnapier** [comment]
Very good stuff. Seems to work, and I think CocoaPods is still happy. If we need to change the version labelling scheme (which is fine), the podfile will need a small change for that. Not sure if changing that creates any upgrade problems (I believe the answer is 'no'). Haven't checked Carthage yet, but I expect it to be ok.

RNCryptor.h is currently imported as the bridging header via the xcodeproj. Might need to touchup the README, but looks like it should be a very small change there. Very exciting.

**Comment by verticon** [comment]
## Carthage
I created a Cartfile that specifies a dependency on the master branch (there is not yet a new tag) of RNCryptor. Running `carthage update` successfully builds the Mac and iOS versions. As we had learned previously, Carthage (actually, xcodebuild) complains about not being able to open the KeyDerivation.playground file - this is a benign warning. One thing about this that I had not previously pointed out: if there is a project file and a workspace file that both contain the same schemes, then Carthage will choose to use the workspace file. Hence the KeyDerivation workspace is being used, which causes the playground file to be encountered.

## CocoaPods

- I ran `pod lib lint` and it passed.
- I cannot run `pod spec lint RNCryptor.podspec` until a new tag is put on the GitHub repo.
- I cannot test the installation of the pod into a project via a pod file: AFAIK that will require pushing a new version to the CocoaPods trunk.
- Changing the version labeling scheme will affect  how the GitHub repo's tag is specified in the pod spec but will not affect how users of the RNCryptor pod write their pod files; the version labels on  CocoaPods do not use the 'RNCyptor' prefix. (Maybe you were thinking something else with regard to upgrades?)

**Comment by verticon** [comment]
BTW: I am very happy to have made my first FOSS contribution!

**Comment by mrtsamma** [comment]
@verticon Great work! I really appreciate it! 
It would be great to update README also about the installation via SPM. 😊
https://github.com/RNCryptor/RNCryptor#installation

**Pull request merged**
